apiVersion: v1
kind: Service
metadata:
  name: session-service
  namespace: default
  labels:
    app: session-service
spec:
  type: ClusterIP
  selector:
    app: session-service
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  sessionAffinity: None

