apiVersion: v1
kind: Service
metadata:
  name: lakeside-frontend
  namespace: default
  labels:
    app: lakeside-frontend
spec:
  type: ClusterIP
  selector:
    app: lakeside-frontend
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  sessionAffinity: None
